apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngrok-ingress
  namespace: {{ .Release.Name }}
  labels:
    app: ngrok-ingress
spec:
  ingressClassName: ngrok
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: /api/score
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend  # Your Node.js service
                port:
                  number: 3000
          - path: /api/leaderboard
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend  # Your Node.js service
                port:
                  number: 3000                    
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-cluster
                port:
                  number: 80
