apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}-cluster
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - name: http
      targetPort: {{ .Values.frontend.service.targetPort }}
      port: {{ .Values.frontend.service.port }}

---

apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}-nodeport
  namespace: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - name: http
      targetPort: {{ .Values.frontend.service.targetPort }}
      port: {{ .Values.frontend.service.port }}
      nodePort: {{ .Values.frontend.service.nodePort }}
