apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: 80   