apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: {{ .Release.Name }}-volume
              mountPath: /usr/share/nginx/html       